//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class MainWindow
    {
        public static readonly string ApplicationThemeLabel = "Localization.MainWindow.ApplicationThemeLabel";
        public static readonly string ThemeDark = "Localization.MainWindow.ThemeDark";
        public static readonly string ThemeLight = "Localization.MainWindow.ThemeLight";
        public static readonly string MarkdownThemeColorLabel = "Localization.MainWindow.MarkdownThemeColorLabel";
        public static readonly string MarkdownThemeSelectPlaceholder = "Localization.MainWindow.MarkdownThemeSelectPlaceholder";
        public static readonly string ApplicationLanguageLabel = "Localization.MainWindow.ApplicationLanguageLabel";
        public static readonly string ApplicationLanguageSelectPlaceholder = "Localization.MainWindow.ApplicationLanguageSelectPlaceholder";
        public static readonly string SampleMarkdownFileLabel = "Localization.MainWindow.SampleMarkdownFileLabel";
    }
}
